/****************************************************************
*   ChordFind - an application to determine possible chords     *
*   from a sequence of notes.                                   *
*****************************************************************/
package ChordFind;

import javax.swing.JOptionPane;
import ChordFind.*;

/**
 *
 * @author Josh Revell
 */
public class winMain extends javax.swing.JFrame {

    /**
     * Creates new form winMain
     */
    public winMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnClearTwo = new javax.swing.JButton();
        btnClearThree = new javax.swing.JButton();
        btnClearFour = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstNoteFour = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNoteThree = new javax.swing.JList<>();
        lstNote2 = new javax.swing.JScrollPane();
        lstNoteTwo = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNoteOne = new javax.swing.JList<>();
        btnClearOne = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDetermineChord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        btnClearTwo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClearTwo.setText("clear");
        btnClearTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTwoActionPerformed(evt);
            }
        });

        btnClearThree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClearThree.setText("clear");
        btnClearThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearThreeActionPerformed(evt);
            }
        });

        btnClearFour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClearFour.setText("clear");
        btnClearFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFourActionPerformed(evt);
            }
        });

        lstNoteFour.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lstNoteFour.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstNoteFour);

        lstNoteThree.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lstNoteThree.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstNoteThree);

        lstNoteTwo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lstNoteTwo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstNote2.setViewportView(lstNoteTwo);

        lstNoteOne.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lstNoteOne.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstNoteOne);

        btnClearOne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClearOne.setText("clear");
        btnClearOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearOne))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearTwo))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearThree))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearFour))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lstNote2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearOne)
                    .addComponent(btnClearTwo)
                    .addComponent(btnClearThree)
                    .addComponent(btnClearFour))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Rage Italic", 1, 52)); // NOI18N
        jLabel5.setText("ChordFind");
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnDetermineChord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDetermineChord.setText("Determine Chord");
        btnDetermineChord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetermineChordActionPerformed(evt);
            }
        });
        jPanel3.add(btnDetermineChord);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetermineChordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetermineChordActionPerformed
        int noteOneIndex = ChromaticScale.getNoteIndex(lstNoteOne.getSelectedValue());
        int noteTwoIndex = ChromaticScale.getNoteIndex(lstNoteTwo.getSelectedValue());
        int noteThreeIndex = ChromaticScale.getNoteIndex(lstNoteThree.getSelectedValue());
        int noteFourIndex = ChromaticScale.getNoteIndex(lstNoteFour.getSelectedValue());
        
        ChordAnalysis analysis;
        
        if (noteOneIndex!=12)
        {
            analysis = new ChordAnalysis(noteOneIndex, noteTwoIndex, 
                    noteThreeIndex, noteFourIndex);
            JOptionPane.showMessageDialog(rootPane, analysis.getChordResults());
        }
        
        if (noteTwoIndex!=12)
        {
            analysis = new ChordAnalysis(noteTwoIndex, noteOneIndex, 
                    noteOneIndex, noteFourIndex);
            JOptionPane.showMessageDialog(rootPane, analysis.getChordResults());
        }
        
        if (noteThreeIndex!=12)
        {
            analysis = new ChordAnalysis(noteThreeIndex, noteTwoIndex, 
                    noteThreeIndex, noteOneIndex);
            JOptionPane.showMessageDialog(rootPane, analysis.getChordResults());
        }
        
        if (noteFourIndex!=12)
        {
            analysis = new ChordAnalysis(noteFourIndex, noteTwoIndex, 
                    noteThreeIndex, noteFourIndex);
            JOptionPane.showMessageDialog(rootPane, analysis.getChordResults());
        }    
    }//GEN-LAST:event_btnDetermineChordActionPerformed

    private void btnClearOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOneActionPerformed
        lstNoteOne.clearSelection();
    }//GEN-LAST:event_btnClearOneActionPerformed

    private void btnClearTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTwoActionPerformed
        lstNoteTwo.clearSelection();
    }//GEN-LAST:event_btnClearTwoActionPerformed

    private void btnClearThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearThreeActionPerformed
        lstNoteThree.clearSelection();
    }//GEN-LAST:event_btnClearThreeActionPerformed

    private void btnClearFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFourActionPerformed
        lstNoteFour.clearSelection();
    }//GEN-LAST:event_btnClearFourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new winMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFour;
    private javax.swing.JButton btnClearOne;
    private javax.swing.JButton btnClearThree;
    private javax.swing.JButton btnClearTwo;
    private javax.swing.JButton btnDetermineChord;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane lstNote2;
    private javax.swing.JList<String> lstNoteFour;
    private javax.swing.JList<String> lstNoteOne;
    private javax.swing.JList<String> lstNoteThree;
    private javax.swing.JList<String> lstNoteTwo;
    // End of variables declaration//GEN-END:variables
}
