/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChordFind;

import javax.swing.JOptionPane;
import ChordFind.*;

/**
 *
 * @author Josh Revell
 */
public class winMain extends javax.swing.JFrame {

    /**
     * Creates new form winMain
     */
    public winMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstNoteOne = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNoteThree = new javax.swing.JList<>();
        lstNote2 = new javax.swing.JScrollPane();
        lstNoteTwo = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstNoteFour = new javax.swing.JList<>();
        btnDetermineChord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClearOne = new javax.swing.JButton();
        btnClearTwo = new javax.swing.JButton();
        btnClearFour = new javax.swing.JButton();
        btnClearThree = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstNoteOne.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstNoteOne);

        lstNoteThree.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstNoteThree);

        lstNoteTwo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstNote2.setViewportView(lstNoteTwo);

        lstNoteFour.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "A#/Bb", "B", "C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstNoteFour);

        btnDetermineChord.setText("Determine Chord");
        btnDetermineChord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetermineChordActionPerformed(evt);
            }
        });

        jLabel1.setText("Root*");

        jLabel2.setText("Third");

        jLabel3.setText("Fifth");

        jLabel4.setText("Seventh / Ninth");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ChordFind - Enter a chord with 4 notes or less");

        btnClearOne.setText("clear");
        btnClearOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOneActionPerformed(evt);
            }
        });

        btnClearTwo.setText("clear");
        btnClearTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTwoActionPerformed(evt);
            }
        });

        btnClearFour.setText("clear");
        btnClearFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFourActionPerformed(evt);
            }
        });

        btnClearThree.setText("clear");
        btnClearThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearThreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetermineChord)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(74, 74, 74)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClearOne)
                                .addGap(39, 39, 39)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnClearTwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClearThree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearFour)
                                .addGap(52, 52, 52)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearOne)
                    .addComponent(btnClearFour)
                    .addComponent(btnClearTwo)
                    .addComponent(btnClearThree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnDetermineChord)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetermineChordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetermineChordActionPerformed
        // TODO add your handling code here:
        int noteOneIndex = ChromaticScale.getNoteIndex(lstNoteOne.getSelectedValue());
        int noteTwoIndex = ChromaticScale.getNoteIndex(lstNoteTwo.getSelectedValue());
        int noteThreeIndex = ChromaticScale.getNoteIndex(lstNoteThree.getSelectedValue());
        int noteFourIndex = ChromaticScale.getNoteIndex(lstNoteFour.getSelectedValue());
             
        ChordAnalysis cA = new ChordAnalysis();
        cA.analyze(noteOneIndex, noteTwoIndex, noteThreeIndex, noteFourIndex);
        JOptionPane.showMessageDialog(rootPane, cA.chordResults.toString());
        
    }//GEN-LAST:event_btnDetermineChordActionPerformed

    private void btnClearOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOneActionPerformed
        lstNoteOne.clearSelection();
    }//GEN-LAST:event_btnClearOneActionPerformed

    private void btnClearTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTwoActionPerformed
        lstNoteTwo.clearSelection();
    }//GEN-LAST:event_btnClearTwoActionPerformed

    private void btnClearThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearThreeActionPerformed
        lstNoteThree.clearSelection();
    }//GEN-LAST:event_btnClearThreeActionPerformed

    private void btnClearFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFourActionPerformed
        lstNoteFour.clearSelection();
    }//GEN-LAST:event_btnClearFourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new winMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFour;
    private javax.swing.JButton btnClearOne;
    private javax.swing.JButton btnClearThree;
    private javax.swing.JButton btnClearTwo;
    private javax.swing.JButton btnDetermineChord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane lstNote2;
    private javax.swing.JList<String> lstNoteFour;
    private javax.swing.JList<String> lstNoteOne;
    private javax.swing.JList<String> lstNoteThree;
    private javax.swing.JList<String> lstNoteTwo;
    // End of variables declaration//GEN-END:variables
}
